name: Java-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spec
    runs-on: self-hosted

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn package
        
      - name: Sonarqube
        env:
          SONAR_TOKEN:${{ secrets.SONAR_TOKEN}}
        run: |
          mvn -B verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=sowjigangasani2002-hue_spring-petclinic \
          -Dsonar.organization=owjigangasani2002 \
          -Dsonar.host.url=${SONAR_HOST_URL}  


        
      
        

