name: Java-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my-spec
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn package
        
      - name: Build and anyalse
        uses: SonarSource/sonarqube-scan-action@v4

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
        with:
          args: >
            -Dsonar.organization=sowjigangasani2002-hue
            "-Dsonar.projectName=petclinic" 
            -Dsonar.projectKey=sowjigangasani2002-hue_spring-petclinic

        
      
        

